default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pro
  password: <%= ENV['PRO_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: todo_api_development

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: todo_api_production
  username: todo_api
  password: <%= ENV['TODO_API_DATABASE_PASSWORD'] %>